spring:
  application:
    name: Security
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-on-validation-error: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET:devSecretKeyForLocalDevelopmentOnlyDoNotUseInProductionMustBe256BitsOrMore}
  expiration: 3600000  # 60 minutes in milliseconds



server:
  port: 4040

logging:
  level:
    org.flywaydb: INFO
    org.hibernate.SQL: DEBUG
